name: build-image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: get AWS SDK source code
      uses: actions/checkout@v2
      with:
        path: 'aws-sdk-cpp'
        repository: 'aws/aws-sdk-cpp'
    
    - name: get libpam-dynamo source code
      uses: actions/checkout@v2
      with:
        path: 'source'

    - name: patch AWS SDK for cpack
      run: |
        cd $GITHUB_WORKSPACE/aws-sdk-cpp
        git apply $GITHUB_WORKSPACE/source/aws-sdk-patch.patch

    - name: build AWS CPP SDK (dynamodb only)
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
        mkdir -p $GITHUB_WORKSPACE/sdk_build
        cd $GITHUB_WORKSPACE/sdk_build
        cmake ../aws-sdk-cpp -D CMAKE_BUILD_TYPE=RelWithDebInfo -D BUILD_ONLY="dynamodb"
        make
        cpack -G DEB
        sudo make install
    
    - name: get and build sqlite3 3.31
      run: |
        cd $GITHUB_WORKSPACE
        mkdir sqlite3
        cd sqlite3
        wget https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
        tar xvf sqlite-autoconf-3310100.tar.gz
        cd sqlite-autoconf-3310100
        ./configure
        make
        sudo make install
        cd /usr/lib/x86_64-linux-gnu
        sudo ln -sf /usr/local/lib/libsqlite3.so
        sudo ln -sf /usr/local/lib/libsqlite3.so.0
        cd /usr/include
        sudo ln -sf ../local/include/sqlite3.h
  
    - name: build & package libpam-dynamo
      run: |
        sudo apt-get install -y libpam0g-dev
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DBUILD_SHARED_LIBS=ON -DPAM_DIR=$GITHUB_WORKSPACE/source $GITHUB_WORKSPACE/source
        make
        cpack -G DEB
    
    - name: log in to docker
      run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    
    - name: Get the tag for docker
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::8})
    
    - name: docker build and publish
      run: |
        cd $GITHUB_WORKSPACE/source
        cp $GITHUB_WORKSPACE/build/*.deb .
        cp $GITHUB_WORKSPACE/sdk_build/*.deb .
        cp /usr/local/lib/libsqlite3.so.0 .
        docker build . -t ubuntu-pam-dynamo:${{steps.vars.outputs.tag}}
        docker tag ubuntu-pam-dynamo:${{steps.vars.outputs.tag}} ${{secrets.DOCKERHUB_USERNAME}}/ubuntu-pam-dynamo:${{steps.vars.outputs.tag}}
        docker tag ubuntu-pam-dynamo:${{steps.vars.outputs.tag}} ${{secrets.DOCKERHUB_USERNAME}}/ubuntu-pam-dynamo:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/ubuntu-pam-dynamo:${{steps.vars.outputs.tag}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/ubuntu-pam-dynamo:latest
