name: build-deb-image

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: 'source'

    - name: Get and build AWS SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
        mkdir -p $GITHUB_WORKSPACE/sdk_build
        git clone https://github.com/aws/aws-sdk-cpp.git $GITHUB_WORKSPACE/aws-sdk-cpp
        cd $GITHUB_WORKSPACE/sdk_build
        cmake ../aws-sdk-cpp -D CMAKE_BUILD_TYPE=RelWithDebInfo -D BUILD_ONLY="dynamodb"
        make
        sudo make install
    
    - name: create build directory
      run: mkdir -p $GITHUB_WORKSPACE/build
    
    - name: build libpam-dynamo
      run: |
        sudo apt-get install -y libpam0g-dev
        cd $GITHUB_WORKSPACE/build
        cmake -DBUILD_SHARED_LIBS=ON -DPAM_DIR=../source ../source
        cpack -G DEB
