name: build-deb-image

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: get AWS SDK source code
      uses: actions/checkout@v2
      with:
        path: 'aws-sdk-cpp'
        repository: 'aws/aws-sdk-cpp'

    - name: build AWS CPP SDK (dynamodb only)
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
        mkdir -p $GITHUB_WORKSPACE/sdk_build
        cd $GITHUB_WORKSPACE/sdk_build
        cmake ../aws-sdk-cpp -D CMAKE_BUILD_TYPE=RelWithDebInfo -D BUILD_ONLY="dynamodb"
        make
        sudo make install
    
    - name: get libpam-dynamo source code
      uses: actions/checkout@v2
      with:
        path: 'source'
  
    - name: build & package libpam-dynamo
      run: |
        sudo apt-get install -y libpam0g-dev
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DBUILD_SHARED_LIBS=ON -DPAM_DIR=$GITHUB_WORKSPACE/source $GITHUB_WORKSPACE/source
        make
        cpack -G DEB
